### ISSUE TITLE
Function tracking inside a target

### ISSUE THREAD

**Issue by glep** [ropensci/targets#280]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] For any problems you identify, post a [minimal reproducible example](https://www.tidyverse.org/help/) like [this one](https://github.com/ropensci/targets/issues/256#issuecomment-754229683) so the maintainer can troubleshoot. A reproducible example is:
    * [x] **Runnable**: post enough R code and data so any onlooker can create the error on their own computer.
    * [x] **Minimal**: reduce runtime wherever possible and remove complicated details that are irrelevant to the issue at hand.
    * [x] **Readable**: format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

Hi,
I tried to define a function ```ff``` inside a target for future use.

Doing that, the problem is that if I change a function called by ```ff```, then the target does not become outdated.

It will probably be clearer with a reprex, so here it is.

``` r
targets::tar_script({
  options(crayon.enabled = FALSE)
  library(targets)
  # Set target-specific options such as packages.
  tar_option_set(packages = "tidyverse", error = "workspace")
  
  gg <- function() {
    1
  }
  ff <- function() {
    gg()
  }
  
  # End this file with a list of target objects.
  list(
    tar_target(t1, tibble(label = "t1", n = 100, gaa = list(ff))),
    tar_target(t2, tibble(label = "t2", n = 100, gaa = list(ff))),
    tar_target(comb, list(t1, t2))
  )
  
})
targets::tar_make()
#> * run target t1
#> * run target t2
#> * run target comb
#> * end pipeline

targets::tar_script({
  options(crayon.enabled = FALSE)
  library(targets)
  # Set target-specific options such as packages.
  tar_option_set(packages = "tidyverse", error = "workspace")
  
  gg <- function() {
    2
  }
  ff <- function() {
    gg()
  }
  
  # End this file with a list of target objects.
  list(
    tar_target(t1, tibble(label = "t1", n = 100, gaa = list(ff))),
    tar_target(t2, tibble(label = "t2", n = 100, gaa = list(ff))),
    tar_target(comb, list(t1, t2))
  )
  
})

targets::tar_make()
#> * run target t1
#> * run target t2
#> v skip target comb
#> * end pipeline
```

<sup>Created on 2021-01-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

We can see that when I change my ```gg``` function, targets ```t1``` and ```t2``` are updated but ```comb``` is not.

Is there a way to solve this?

Thanks a lot, have a great day!

**Comment by wlandau** [comment]
This is an interesting case, and it has to do with how invalidation behavior for functions is different from that of actual targets. For functions, we assume that whenever you change an upstream function, all the downstream functions are always invalidated. That is why `t1` and `t2`  rerun when `gg()` changes. But for actual targets, the decision are different. If an upstream target reruns, that doesn't necessarily matter to downstream targets. If the target reran but the hash did not change, this will not invalidate anything downstream. This behavior is usually correct and saves a lot of runtime in practice. Passing functions in the way you demonstrated does present an edge case, but it is not very common.

So in order to rerun, `comb` will need a graph edge directly from `ff` or `gg`. If you call `tar_visnetwork()`, you will see that `comb` only has edges from `t1` and `t2`. If you mention `ff` somewhere in the command of `comb`, you will get the behavior you want.

**Comment by glep** [comment]
Thanks for your answer.

I tried use S3 classes to solve my problem.
But it seems that the dependency between function with ```useMethod``` and class functions is not tracked.
Looking at the following example, one can see with ```tar_visnetwork()``` that there is not link between ```ff.class1``` and ```ff```.

Is there a way to force these dependencies?

``` r
targets::tar_script({
  options(crayon.enabled = FALSE)
  library(targets)
  tar_option_set(packages = "tidyverse", error = "workspace")
  
  ff <- function(x) UseMethod("ff")
  ff.class1 <- function(x) 1
  ff.tbl_df <- function(x) 2
  
  # End this file with a list of target objects.
  list(
    tar_target(
      t1,
      structure(
        tibble(label = "t1", n = 100, gaa = list(ff)),
        class = "class1"
      )
    ),
    tar_target(t2, tibble(label = "t2", n = 100)),
    tar_target(comb, list(t1, t2)),
    tar_target(new, ff(comb[[1]]), pattern = map(comb))
  )
  
})
targets::tar_make()
#> * run target t1
#> * run target t2
#> * run target comb
#> * run branch new_b4ebea21
#> * run branch new_4c3e2b0b
#> * end pipeline

targets::tar_read(new)
#> [1] 1 2

targets::tar_script({
  options(crayon.enabled = FALSE)
  library(targets)
  tar_option_set(packages = "tidyverse", error = "workspace")
  
  ff <- function(x) UseMethod("ff")
  ff.class1 <- function(x) 11
  ff.tbl_df <- function(x) 2
  
  # End this file with a list of target objects.
  list(
    tar_target(
      t1,
      structure(
        tibble(label = "t1", n = 100, gaa = list(ff)),
        class = "class1"
      )
    ),
    tar_target(t2, tibble(label = "t2", n = 100)),
    tar_target(comb, list(t1, t2)),
    tar_target(new, ff(comb[[1]]), pattern = map(comb))
  )
  
}) 
targets::tar_make()
#> v skip target t1
#> v skip target t2
#> v skip target comb
#> v skip branch new_b4ebea21
#> v skip branch new_4c3e2b0b
#> v skip pipeline
targets::tar_read(new)
#> [1] 1 2
```

<sup>Created on 2021-01-22 by the [reprex package](https://reprex.tidyverse.org) (v0.3.0)</sup>

**Comment by wlandau** [comment]
Unfortunately it is not possible to account for S3 because `targets` uses static code analysis to figure out dependency relationships: https://books.ropensci.org/targets/practices.html#dependencies. We cannot predict what S3 dispatch is going to do because we do not know what the class of the target's return value will be.
