### ISSUE TITLE
Log skipped targets in _targets/meta/progress

### ISSUE THREAD

**Issue by wlandau** [ropensci/targets#514]
## Prework

* [x] Read and agree to the [code of conduct](https://ropensci.org/code-of-conduct/) and [contributing guidelines](https://github.com/ropensci/targets/blob/main/CONTRIBUTING.md).
* [x] If there is [already a relevant issue](https://github.com/ropensci/targets/issues), whether open or closed, comment on the existing thread instead of posting a new issue.
* [x] New features take time and effort to create, and they take even more effort to maintain. So if the purpose of the feature is to resolve a struggle you are encountering personally, please consider first posting a "trouble" or "other" issue so we can discuss your use case and search for existing solutions first.
* [x] Format your code according to the [tidyverse style guide](https://style.tidyverse.org/).

## Proposal

When this first came up, I originally decided against it because of the ~6% speed penalty if there are many skipped targets. However, I am realizing how important it is to see skipped targets as part of the overall picture when monitoring progress. Working on a patch to log skipped targets and show them in `tar_progress()`, `tar_poll()`, `tar_watch()`, `tar_progress_branches()`, and `tar_progress_summary()`.

**Comment by wlandau** [comment]
`tar_make(reporter = "silent", callr_function = NULL)` still needs to be fast, and writing skip lines one by one really slowed it down at first. But as of 5bb3132b53bd9e5ebfe923f8d439d1259850f909, Instead of writing each skip line separately to `_targets/meta/progress`, `targets` accumulate skip lines in a queue and then writes them all out in bulk when something interesting happens. Overhead reduced.
