### ISSUE TITLE
Short-term roadmap

### ISSUE THREAD

**Issue by wlandau-lilly** [ropensci/targets#58]
- [x] Add placeholder settings for retrieval and memory.
- [x] Implement counters in the plan for loaded and loaded transient-memory targets.
- [x] Implement transient memory: counting and unloading.
- [x] Implement valueless target cloning.
- [x] Implement scaffold of plan.
- [x] Implement remote retrieval with appropriate memory cleaning.
